phrase:
  project_id: d8b77fd44f98aa3a9793942ac1c66f66 

  push:
    sources:
    - file: ./en.json
      params:
        file_format: simple_json
        locale_id: en
        update_translations: true
          
  pull:
    targets:
    - file: ./it.json
      params:
        file_format: simple_json
        locale_id: it
        include_empty_translations: true
        include_unverified_translations: true
